name: oac
channels:
  - conda-forge
dependencies:
  - joblib
  - platformdirs
  - black
  - lazy-object-proxy
  - numpy
  - pandas
  - pandas-stubs
  - jupyterlab
  - openssl
  - sphinx
  - toml
  - ipykernel
  - scikit-learn
  - matplotlib
  - netcdf4
  - python
  - pytest-cov
  - prospector
  - cf-units
  - xarray
  - pytest-httpserver
  - ca-certificates
  - certifi
  - pylint
  - wrapt
  - mypy
  - beautifulsoup4
  - bottleneck
  - cartopy
  - pytest
  - pyroma
  - isort
  - scipy
  - scipy-stubs
  - ipympl
  - openpyxl
  - deepmerge